"""
signals.py

Two independent detection signals:

1. llm_signal()   - asks an LLM (Groq) to holistically judge whether text
                     reads as human- or AI-written. Captures semantic and
                     stylistic coherence as a whole. Blind spot: an LLM
                     grader can be fooled by short or heavily-edited text,
                     and it can't explain *why* beyond a rationale string.

2. stylometric_signal() - pure-Python statistical measurements (sentence
                     length variance, type-token ratio, punctuation
                     density). Captures structural uniformity, which tends
                     to be lower in AI-generated text and higher in casual
                     human writing. Blind spot: a human writing in a very
                     formal, uniform register (e.g. academic prose) can
                     score similarly to AI text on this signal alone -
                     which is exactly why it must never be used by itself.

Both signals return a float in [0, 1] representing "AI-likelihood",
plus a short human-readable rationale, so the combined score in app.py
can weight and explain them.
"""

import json
import os
import re
import statistics

from dotenv import load_dotenv

load_dotenv()

GROQ_MODEL = "llama-3.3-70b-versatile"


def llm_signal(text: str) -> dict:
    """
    Returns: {"score": float 0-1, "rationale": str}
    Higher score = more likely AI-generated.
    """
    try:
        from groq import Groq

        client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

        prompt = (
            "You are an assistant that assesses whether a piece of writing "
            "was generated by an AI language model or written by a human. "
            "Respond with ONLY a JSON object, no other text, in this exact "
            'shape: {"ai_likelihood": <float between 0 and 1>, '
            '"rationale": "<one sentence>"}.\n\n'
            "Text to assess:\n"
            f"---\n{text}\n---"
        )

        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=200,
        )

        raw = response.choices[0].message.content.strip()
        raw = re.sub(r"^```(json)?|```$", "", raw.strip(), flags=re.MULTILINE).strip()
        parsed = json.loads(raw)
        score = float(parsed.get("ai_likelihood", 0.5))
        score = min(max(score, 0.0), 1.0)
        return {"score": score, "rationale": parsed.get("rationale", "")}

    except Exception as e:
        # Fail safe: if the LLM call breaks (no key, network, bad parse),
        # return a neutral score rather than crashing the request, and
        # say why in the rationale so it's visible in the audit log.
        return {"score": 0.5, "rationale": f"llm_signal_error: {e}"}


def stylometric_signal(text: str) -> dict:
    """
    Returns: {"score": float 0-1, "rationale": str, "metrics": {...}}
    Higher score = more likely AI-generated (more structurally uniform).
    """
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]
    words = re.findall(r"[A-Za-z']+", text.lower())

    if len(sentences) < 2 or len(words) < 10:
        # Not enough signal to say anything meaningful - stay neutral.
        return {
            "score": 0.5,
            "rationale": "Text too short for reliable stylometric analysis.",
            "metrics": {},
        }

    # 1. Sentence length variance (in words). Low variance -> more uniform -> more AI-like.
    lengths = [len(re.findall(r"[A-Za-z']+", s)) for s in sentences]
    length_variance = statistics.pvariance(lengths) if len(lengths) > 1 else 0.0
    # Normalize: variance of ~40+ is "clearly variable", ~0-5 is "clearly uniform"
    variance_score = 1.0 - min(length_variance / 40.0, 1.0)

    # 2. Type-token ratio (vocabulary diversity). Low TTR -> more repetitive -> more AI-like.
    ttr = len(set(words)) / len(words)
    # Typical human casual writing TTR ~0.55-0.75 for short passages; lower ratio -> higher AI score
    ttr_score = 1.0 - min(ttr / 0.75, 1.0)

    # 3. Punctuation density (commas/semicolons per sentence). AI text tends to
    #    over-use structuring punctuation like semicolons and "furthermore"-style commas.
    punct_count = len(re.findall(r"[;:]", text)) + text.count(", ")
    punct_density = punct_count / len(sentences)
    punct_score = min(punct_density / 3.0, 1.0)

    combined = (0.45 * variance_score) + (0.35 * ttr_score) + (0.20 * punct_score)
    combined = min(max(combined, 0.0), 1.0)

    return {
        "score": combined,
        "rationale": (
            f"sentence-length variance={length_variance:.1f}, "
            f"type-token ratio={ttr:.2f}, punctuation density={punct_density:.2f}"
        ),
        "metrics": {
            "sentence_length_variance": round(length_variance, 2),
            "type_token_ratio": round(ttr, 3),
            "punctuation_density": round(punct_density, 3),
        },
    }